apiVersion: v1
kind: Secret
metadata:
  name: {{ include "document-embedding.name" . }}
  labels:
    {{- include "document-embedding.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-

    kafka.bootstrap.servers={{ .Values.kafka.bootstrapServer }}

    {{- if .Values.kafka.securityProtocol }}
    mp.messaging.connector.smallrye-kafka.security.protocol={{ .Values.kafka.securityProtocol }}
    {{- end }}
    {{- if .Values.kafka.saslMechanism }}
    mp.messaging.connector.smallrye-kafka.sasl.mechanism={{ .Values.kafka.saslMechanism }}
    {{- end }}

    {{- if eq .Values.kafka.saslMechanism "PLAIN" }}
    mp.messaging.connector.smallrye-kafka.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
      username="{{ .Values.kafka.clientId }}" \
      password="{{ .Values.kafka.clientSecret }}" ;
    {{- end }}
    {{- if eq .Values.kafka.saslMechanism "SCRAM-SHA-512" }}
    mp.messaging.connector.smallrye-kafka.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
      username="{{ .Values.kafka.clientId }}" \
      password="{{ .Values.kafka.clientSecret }}" ;
    {{- end }}

    mp.messaging.incoming.documents.topic={{ .Values.kafka.topic.documents }}
    mp.messaging.incoming.documents.group.id={{ .Values.kafka.consumerGroup.documents }}

    langchain4j.openai.base-url={{ .Values.embedding.baseUrl }}
    langchain4j.openai.model-name={{ .Values.embedding.modelName }}
    langchain4j.openai.api-key={{ .Values.embedding.apiKey }}
    langchain4j.openai.timeout={{ .Values.embedding.timeout }}
    langchain4j.openai.dimension={{ .Values.embedding.dimension }}
    langchain4j.openai.set-dimension={{ .Values.embedding.setDimension }}

    milvus.uri={{ .Values.milvus.url }}
    milvus.username={{ .Values.milvus.username }}
    milvus.password={{ .Values.milvus.password }}
    milvus.collection-name={{ .Values.milvus.collection }}
    milvus.drop-collection={{ .Values.milvus.dropCollection }}
    milvus.dimension={{ .Values.milvus.dimension }}