apiVersion: v1
kind: Secret
metadata:
  name: {{ include "customer-data.name" . }}
  labels:
    {{- include "customer-data.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-

    kafka.bootstrap.servers={{ .Values.kafka.bootstrapServer }}

    {{- if .Values.kafka.securityProtocol }}
    mp.messaging.connector.smallrye-kafka.security.protocol={{ .Values.kafka.securityProtocol }}
    {{- end }}
    {{- if .Values.kafka.saslMechanism }}
    mp.messaging.connector.smallrye-kafka.sasl.mechanism={{ .Values.kafka.saslMechanism }}
    {{- end }}

    {{- if eq .Values.kafka.saslMechanism "PLAIN" }}
    mp.messaging.connector.smallrye-kafka.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
      username="{{ .Values.kafka.clientId }}" \
      password="{{ .Values.kafka.clientSecret }}" ;
    {{- end }}
    {{- if eq .Values.kafka.saslMechanism "SCRAM-SHA-512" }}
    mp.messaging.connector.smallrye-kafka.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required \
      username="{{ .Values.kafka.clientId }}" \
      password="{{ .Values.kafka.clientSecret }}" ;
    {{- end }}

    mp.messaging.incoming.message.topic={{ .Values.kafka.topic.intake }}
    mp.messaging.incoming.message.group.id={{ .Values.kafka.consumerGroup.intake }}

    mp.messaging.outgoing.customer-data.topic={{ .Values.kafka.topic.outflow }}
    mp.messaging.outgoing.error.topic={{ .Values.kafka.topic.error }}

    quarkus.datasource.username={{ .Values.datasource.username }}
    quarkus.datasource.password={{ .Values.datasource.password }}
    quarkus.datasource.jdbc.url=jdbc:postgresql://{{ .Values.datasource.url }}/{{ .Values.datasource.database }}
